### ISSUE TITLE
DestopLiveStreamer Stop Working !

### ISSUE THREAD

**Issue by ryuroker** [charnet3d/DesktopLiveStreamer#19]
I'm using this softwere fro 2 months, and now, not work more =S also for my friend, at same time. Sorry for my english.

**Comment by derbol** [comment]
Same problem for me.
It seems it cannot load the stream quality info anymore.
I tried to update livestreamer, but that didn't do it.
thanks in advance!

**Comment by ryuroker** [comment]
hope they will fix it =(, i don't know what use for the moment, this software is the best =(

**Comment by Kitt213** [comment]
i hope they fix it too . i use desktop live streamer everyday

**Comment by ryuroker** [comment]
seem a Livestream problem, so all the software for these things, now not working =(

**Comment by Dr-PJA** [comment]
Livestream update to 1.11.1 https://github.com/chrippa/livestreamer/releases/download/v1.11.1/livestreamer-v1.11.1-win32.zip

**Comment by charnet3d** [comment]
Hi everyone,
I tried the 1.11.1 livestreamer update and it seems to fix the problem.

Now that I showed up here, I wanted to express my deep apologies for not maintaining the project for so long (almost a year since last update!), I've been focusing on some other life projects and I neglected it really badly.

I'm seriously thinking about getting back to it and fixing the most serious flaws in it (the most important being some sort of update system, even for livestreamer, that could make updating a little less painful for all of us). I'm also working on a website where I could showcase my projects and portfolio, and thus also giving DLS a more official home page.

**Comment by ryuroker** [comment]
Nice =) Thank for what are you doing.

**Comment by ryuroker** [comment]
Hi, should be usefull, a way for open more streams, and when you close one stream, don't close the first, and another thing, a way for record stream without audio. Vods channel are so popular, should help a lot of people. =)

**Comment by Kitt213** [comment]
being able to record more then 1 at the same time opening multiple vlc without it crashing when they end would be magical . currently i have to use multiple Vmware workstation to do it, but its highly resource demanding .
