### ISSUE TITLE
Add stream from thestreamdb site

### ISSUE THREAD

**Issue by DGMurdockIII** [charnet3d/DesktopLiveStreamer#21]
Can you add support for the streams listed on the this site
http://www.thestreamdb.com/

**Comment by charnet3d** [comment]
I'm not the one responsible for adding support for other streaming sites, you should refer to the livestreamer utility (that I use under the hood) to ask them for that feature if they can implement it.

Here are the plugins they support currently: http://docs.livestreamer.io/plugin_matrix.html

Here's their github page: https://github.com/chrippa/livestreamer

**Comment by DGMurdockIII** [comment]
i was asking to the gui the already have the livestreamer url there

**Comment by charnet3d** [comment]
um I'm not sure I understand your last comment very well.
If you think that the livestreamer utility does support the URL you want to play, you can use the favorites to add it to the GUI:
- Select the favourites frame, and click Add
- give a name to the stream entry, paste the stream URL and use one of these qualities "best" or "worst" (without quotes). These should always work.

Try playing your new favourite, if it plays then good, otherwise it's most likely because that streaming site's URL isn't supported.
